name: semantic-versioning
on:
  pull-request:
    types: closed
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}